---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - name: mongodb
    imagePullPolicy: Always
    image: naveenreddy369/mongodb:k8
    ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017

#We are noot going to exposing this mongodb to outside world, so we need to use ClusteIP service. Since it is the default one no need to mention.