---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
   MYSQL_DATABASE= "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-mysecret
type: Opaque
data:
  username: c2hpcHBpbmc=
  password: c2VjcmV0
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: naveenreddy369/mysql:k8
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretKeyRef:
        name: mysql-secret
    ports:
      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306



# A Secret is an object that contains a small amount of sensitive data such as a password, a token, or a key. 
# Opaque is the default Secret type
# nkumarr1@INLEN8520046081 MINGW64 ~/OneDrive - Capgemini/Desktop/myrepo/k8-roboshop (main)
# $ echo -n shipping | base64
# c2hpcHBpbmc=

# nkumarr1@INLEN8520046081 MINGW64 ~/OneDrive - Capgemini/Desktop/myrepo/k8-roboshop (main)
# $ echo -n secret | base64
# c2VjcmV0
