---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - name: web
    imagePullPolicy: Always
    image: naveenreddy369/web:k8
    resources:
      requests:
        cpu: "100m"        #represents 100 milliCPU or 0.1 CPU
        memory: "128Mi"    #represents 128 Mebibytes of memory
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
